spring:
  application:
    name: cooperative-voting-api
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:votacao}
    username: ${DB_USER:votacao}
    password: ${DB_PASSWORD:votacao}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

app:
  external:
    user-info-url: https://user-info.herokuapp.com
    timeout-seconds: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
