CREATE TABLE agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    session_opened_at TIMESTAMP,
    session_closes_at TIMESTAMP
);

CREATE TABLE vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agenda_id BIGINT NOT NULL REFERENCES agenda(id),
    member_cpf VARCHAR(11) NOT NULL,
    vote VARCHAR(3) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_vote_agenda_cpf UNIQUE (agenda_id, member_cpf)
);

CREATE INDEX idx_vote_agenda_id ON vote (agenda_id);