CREATE TABLE pauta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descricao VARCHAR(2000),
    criada_em TIMESTAMP NOT NULL,
    sessao_aberta_em TIMESTAMP,
    sessao_fecha_em TIMESTAMP
);

CREATE TABLE voto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL REFERENCES pauta(id),
    cpf_associado CHAR(11) NOT NULL,
    voto VARCHAR(3) NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT uk_voto_pauta_cpf UNIQUE (pauta_id, cpf_associado)
);

CREATE INDEX idx_voto_pauta_id ON voto (pauta_id);
